version: "3.9"
services:
  frontend:
    build:
      context: ./calendar-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  backend:
    build:
      context: ./fastapi-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  #   environment:
  #     - MYSQL_HOST=db
  #     - MYSQL_PORT=3306
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=mysecretpassword
  #     - MYSQL_DB=mydatabase

  # db:
  #   image: mysql:latest
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=mysecretpassword
  #     - MYSQL_DATABASE=mydatabase
  #   ports:
  #     - 3306:3306